/**
 * Notification Type Constants
 * 
 * Centralized constants for notification types across all modules.
 * These are used as the 'type' field in notifications.
 * 
 * Usage:
 *   import { COURSE_ENROLL_APPROVED } from './notificationTypes';
 *   emitNotification({ ..., type: COURSE_ENROLL_APPROVED });
 * 
 * NOTE: These are constants ONLY. No logic or functions here.
 */

// Course-related notifications
const COURSE_ENROLL_REQUESTED = 'COURSE_ENROLL_REQUESTED';
const COURSE_ENROLL_APPROVED = 'COURSE_ENROLL_APPROVED';
const COURSE_ENROLL_REJECTED = 'COURSE_ENROLL_REJECTED';
const COURSE_ENROLL_EXPIRED = 'COURSE_ENROLL_EXPIRED';
const COURSE_PUBLISHED = 'COURSE_PUBLISHED';
const COURSE_COMPLETED = 'COURSE_COMPLETED';
const COURSE_FULL = 'COURSE_FULL';
const COURSE_INVITE_SENT = 'COURSE_INVITE_SENT';

// Video-related notifications
const VIDEO_UPLOADED = 'VIDEO_UPLOADED';
const VIDEO_READY = 'VIDEO_READY';
const VIDEO_MCQ_PUBLISHED = 'VIDEO_MCQ_PUBLISHED';
const VIDEO_TRANSCODING_FAILED = 'VIDEO_TRANSCODING_FAILED';

// Social-related notifications
const POST_LIKED = 'POST_LIKED';
const POST_COMMENTED = 'POST_COMMENTED';
const REEL_LIKED = 'REEL_LIKED';
const FRIEND_REQUEST_RECEIVED = 'FRIEND_REQUEST_RECEIVED';
const FRIEND_REQUEST_ACCEPTED = 'FRIEND_REQUEST_ACCEPTED';
const MESSAGE_RECEIVED = 'MESSAGE_RECEIVED';

// Marketplace-related notifications
const PRODUCT_PURCHASED = 'PRODUCT_PURCHASED';
const PRODUCT_SHIPPED = 'PRODUCT_SHIPPED';
const PRODUCT_DELIVERED = 'PRODUCT_DELIVERED';
const ORDER_PLACED = 'ORDER_PLACED';
const ORDER_CANCELLED = 'ORDER_CANCELLED';
const ORDER_REFUNDED = 'ORDER_REFUNDED';
const SELLER_APPLICATION_APPROVED = 'SELLER_APPLICATION_APPROVED';
const SELLER_APPLICATION_REJECTED = 'SELLER_APPLICATION_REJECTED';

// Wallet-related notifications
const TOKEN_CREDITED = 'TOKEN_CREDITED';
const TOKEN_DEBITED = 'TOKEN_DEBITED';
const REWARD_EARNED = 'REWARD_EARNED';
const PAYMENT_SUCCESS = 'PAYMENT_SUCCESS';
const PAYMENT_FAILED = 'PAYMENT_FAILED';

// System-related notifications
const SYSTEM_ALERT = 'SYSTEM_ALERT';
const SYSTEM_MAINTENANCE = 'SYSTEM_MAINTENANCE';
const ACCOUNT_VERIFIED = 'ACCOUNT_VERIFIED';
const ACCOUNT_SUSPENDED = 'ACCOUNT_SUSPENDED';
const PASSWORD_CHANGED = 'PASSWORD_CHANGED';
const EMAIL_VERIFIED = 'EMAIL_VERIFIED';

module.exports = {
    // Course
    COURSE_ENROLL_REQUESTED,
    COURSE_ENROLL_APPROVED,
    COURSE_ENROLL_REJECTED,
    COURSE_ENROLL_EXPIRED,
    COURSE_PUBLISHED,
    COURSE_COMPLETED,
    COURSE_FULL,
    COURSE_INVITE_SENT,
    
    // Video
    VIDEO_UPLOADED,
    VIDEO_READY,
    VIDEO_MCQ_PUBLISHED,
    VIDEO_TRANSCODING_FAILED,
    
    // Social
    POST_LIKED,
    POST_COMMENTED,
    REEL_LIKED,
    FRIEND_REQUEST_RECEIVED,
    FRIEND_REQUEST_ACCEPTED,
    MESSAGE_RECEIVED,
    
    // Marketplace
    PRODUCT_PURCHASED,
    PRODUCT_SHIPPED,
    PRODUCT_DELIVERED,
    ORDER_PLACED,
    ORDER_CANCELLED,
    ORDER_REFUNDED,
    SELLER_APPLICATION_APPROVED,
    SELLER_APPLICATION_REJECTED,
    
    // Wallet
    TOKEN_CREDITED,
    TOKEN_DEBITED,
    REWARD_EARNED,
    PAYMENT_SUCCESS,
    PAYMENT_FAILED,
    
    // System
    SYSTEM_ALERT,
    SYSTEM_MAINTENANCE,
    ACCOUNT_VERIFIED,
    ACCOUNT_SUSPENDED,
    PASSWORD_CHANGED,
    EMAIL_VERIFIED
};
